services:
  app_1:
    build: ./app_node
    container_name: nombre_app_1
    networks:
      - red2
    environment:
      - DB_HOST=bbdd_1
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=monolito
      - DB_PORT=5432
    ports:
      - "3001:3000"
    depends_on:
      - bbdd_1

  bbdd_1:
    build: ./postgres
    container_name: bbdd_1
    networks:
      - red2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: monolito
    volumes:
      - datos_postgres_1:/var/lib/postgresql/data

  app_2:
    build: ./app_node
    container_name: nombre_app_2
    networks:
      - red2
    environment:
      - DB_HOST=bbdd_2
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=monolito
      - DB_PORT=5432
    ports:
      - "3003:3000"
    depends_on:
      - bbdd_2

  bbdd_2:
    build: ./postgres
    container_name: bbdd_2
    networks:
      - red2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: monolito
    volumes:
      - datos_postgres_2:/var/lib/postgresql/data

networks:
  red2:
    driver: bridge

volumes:
  datos_postgres_1:
  datos_postgres_2:
