services:
  app_1:
    build: ./app_node
    container_name: app_1
    networks:
      - red2
    environment:
      - DB_HOST=bbdd_1
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=usuarios_db_1
    ports:
      - "3001:3000"
    depends_on:
      - bbdd_1

  bbdd_1:
    build: ./app_bbdd
    container_name: bbdd_1
    networks:
      - red2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usuarios_db_1
    volumes:
      - datos_postgres_1:/var/lib/postgresql/data

  app_2:
    build: ./app_node
    container_name: app_2
    networks:
      - red2
    environment:
      - DB_HOST=bbdd_2
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=usuarios_db_2
    ports:
      - "3003:3000"
    depends_on:
      - bbdd_2

  bbdd_2:
    build: ./app_bbdd
    container_name: bbdd_2
    networks:
      - red2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usuarios_db_2
    volumes:
      - datos_postgres_2:/var/lib/postgresql/data

networks:
  red2:
    driver: bridge

volumes:
  datos_postgres_1:
    driver: local
  datos_postgres_2:
    driver: local
